# source files
SRC = gol.cpp

# include directories
INCDIRS = -I../

# library directories
LIBDIRS =

# compiler
CC = g++

# compiler flags
CFLAGS = -std=c++11 -O0 -W -g -Wall -Wextra -pedantic -lglut -lGL -lOpenCL

out: $(SRC)
	$(CC) $(SRC) $(CFLAGS) $(INCDIRS) $(LIBDIRS)
